version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: fcr_postgres
    env_file: ./db/.env
    environment:
      - TZ=America/Bogota
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: fcr_pgadmin
    env_file: ./db/.env
    environment:
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER='"Bienvenido a pgAdmin"'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./db/pgadmin/servers.json:/pgadmin4/servers.json:ro
    depends_on: [postgres]
    restart: unless-stopped

  api_fr:
    build: { context: ./backend/fr, target: prod }
    container_name: fcr_api_fr
    env_file: ./backend/fr/.env
    depends_on: [postgres]
    restart: unless-stopped

  api_socket:
    build: { context: ./backend/socket, target: prod }
    container_name: fcr_api_socket
    env_file: ./backend/socket/.env
    depends_on: [postgres]
    command: ["gunicorn","-k","uvicorn.workers.UvicornWorker","-w","1","-t","1","-b","0.0.0.0:80","main:app"]
    restart: unless-stopped

  front_fr:
    build: { context: ./frontend/fr, target: prod }
    container_name: fcr_front_fr
    env_file: ./frontend/fr/.env_prod
    restart: unless-stopped

  proxy:
    build: { context: ./nginx }
    container_name: fcr_proxy
    ports: [ '80:80', '443:443' ]
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./nginx/proxy_params.conf:/etc/nginx/proxy_params.conf:ro
      - ./nginx/certbot/www:/var/www/certbot:ro
      - ./nginx/letsencrypt:/etc/letsencrypt:ro
    depends_on: [postgres, pgadmin, api_fr, api_socket, front_fr]
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: fcr_certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/letsencrypt:/etc/letsencrypt
    depends_on: [proxy]
    entrypoint: sh
    command: -c "if [ -n 'api.fr.fresasconcrema.co api.socket.fcr.fresasconcrema.co fr.fresasconcrema.co pgadmin.fresasconcrema.co www.fr.fresasconcrema.co' ]; then for d in api.fr.fresasconcrema.co api.socket.fcr.fresasconcrema.co fr.fresasconcrema.co pgadmin.fresasconcrema.co www.fr.fresasconcrema.co; do certbot certonly -n --keep-until-expiring --webroot -w /var/www/certbot -d $$d --email \"andrew19f@gmail.com\" --agree-tos --no-eff-email ; done; fi; trap exit TERM; while :; do certbot renew -n --webroot -w /var/www/certbot --quiet || true; sleep 12h; done"
    restart: unless-stopped

volumes:
  pg_data:
  pgadmin_data:
